added mutiple scanner checking, and categorized scan dates now have the session uid

diff --git a/bin/check_heartbeat b/bin/check_heartbeat
--- a/bin/check_heartbeat
+++ b/bin/check_heartbeat
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 CmdName=$(basename "$0")
-Syntax="${CmdName} [-c YYYY-MM-DD][-g GroupId][-m YYYY-MM-DD][-p ProjectLabel][-w YYYY-MM-DD] [Scanner]" 
+Syntax="${CmdName} [-c YYYY-MM-DD][-g GroupId][-m YYYY-MM-DD][-n][-p ProjectLabel][-w YYYY-MM-DD][-v] [Scanner]" 
 
 FwDir=$(dirname $(dirname $(realpath "$0")))
 
@@ -11,70 +11,7 @@ export PYTHONPATH="${FwDir}/lib"
 ScannerMapJsonFile="${FwDir}/etc/ScannerMap.json"
 ScannerStationNamesJsonFile="${FwDir}/etc/ScannerStationNames.json"
 
-while getopts c:g:m:p:w: arg
-do
-	case "$arg" in
-	     c|g|m|p|w)
-		eval "opt_${arg}='${OPTARG:=1}'"
-		;;
-	esac
-done
-
-shift $(($OPTIND - 1))
-
-CriticalDate=$(date --date='2 days ago' +%Y-%m-%d)
-[ -n "$opt_c" ] && CriticalDate="$opt_c"
-
-GroupId=camris
-[ -n "$opt_g" ] && GroupId="$opt_g"
-
-MonthAgoDate=$(date --date='2 months ago' +%Y-%m-%d)
-[ -n "$opt_m" ] && MonthAgoDateDate="$opt_m"
-
-ProjectLabel=qa
-[ -n "$opt_p" ] && ProjectLabel="$opt_p"
-
-WarningDate=$(date --date='1 day ago' +%Y-%m-%d)
-[ -n "$opt_w" ] && WarningDate="$opt_w"
-
-ValidScanners=$(jq -r ".[]" "$ScannerMapJsonFile" "$ScannerStationNamesJsonFile" | sort -u)
-
-if [ -z "$1" ]
-then
-	echo "$Syntax" 1>&2
-	echo "Scanner must be one of: " 1>&2	
-	echo "$ValidScanners" 1>&2
-
-	exit 1
-else
-	if echo "$ValidScanners" | grep -q "$1"
-	then
-		Scanner="$1"
-	else
-		echo "$Syntax" 1>&2
-		echo "'$1' not found in list of valid scanners: " 1>&2
-		echo "$ValidScanners" 1>&2
-
-		exit 2
-	fi
-fi	
-
-CategorizedScanDatesFile=$(mktemp "/tmp/${CmdName}CategorizedScanDates-XXXXXX")
-
-
-CategorizeCreatedDateJq='
-  .session.created | sub("T.*$";"") as $CreatedDate
-| if ($CreatedDate >= $WarningDate) then
-      "Ok "
-  else if ($CreatedDate > $CriticalDate and $CreatedDate <= $WarningDate) then
-        "Warning "
-     else
-         "Critical "
-     end
-  end + $CreatedDate
-'
-
-function getScannerSessionsJson {
+function getScanSessionAfterJson {
 	local Scanner="$1"
 	local GroupId="$2"
 	local ProjectLabel="$3"
@@ -101,32 +38,111 @@ function getScannerSessionsJson {
 	fi
 }
 
-getScannerSessionsJson "$Scanner" "$GroupId" "$ProjectLabel" "$MonthAgoDate" | jq -r --argjson WarningDate "\"$WarningDate\"" --argjson CriticalDate "\"$CriticalDate\"" "$CategorizeCreatedDateJq" > "$CategorizedScanDatesFile"
+function checkScannerHeartbeat {
+    local Scanner="$1"
 
+    local ValidScanners=$(jq -r ".[]" "$ScannerMapJsonFile" "$ScannerStationNamesJsonFile" | sort -u)
 
-OkCount=$(grep "Ok" "$CategorizedScanDatesFile" | wc -l)
-WarningCount=$(grep "Warning" "$CategorizedScanDatesFile" | wc -l)
-
-if [ "$OkCount" -gt 0 ]
-then
-	Msg="OK - ${OkCount} scan(s) in ${GroupId}/${ProjectLabel} from ${Scanner} since ${WarningDate}"
-	ExitCode=0
-elif [ "$WarningCount" -gt 0 ]
-then
-	Msg="Warning - ${WarningCount} scan(s) in ${GroupId}/${ProjectLabel} from ${Scanner} between ${CriticalDate} and ${WarningDate}"
-	ExitCode=1
-else
-	LastScanSeenDate=$(grep Critical "$CategorizedScanDatesFile" | sort | tail -n 1 | cut -f 2 -d ' ')
-	if [ -z "$LastScanSeenDate" ]
+	if [ -z "$Scanner" ]
 	then
-		Msg="CRITICAL - No scans seen in ${GroupId}/${ProjectLabel} from ${Scanner} after ${MonthAgoDate}"
+		echo "$Syntax" 1>&2
+		echo "Scanner must be one of: " 1>&2	
+		echo "$ValidScanners" 1>&2
+	
+		exit 1
 	else
-		Msg="CRITICAL - Last scan in ${GroupId}/${ProjectLabel} from ${Scanner} seen on ${LastScanSeenDate}"
+		if echo "$ValidScanners" | grep -q "$1"
+		then
+			Scanner="$1"
+		else
+			echo "$Syntax" 1>&2
+			echo "'$1' not found in list of valid scanners: " 1>&2
+			echo "$ValidScanners" 1>&2
+	
+			exit 2
+		fi
+	fi	
+	
+	CategorizedScanDatesFile=$(mktemp "/tmp/${CmdName}CategorizedScanDates${Scanner}-XXXXXX")
+	
+	CategorizeCreatedDateJq='
+	  ( .session.created | sub("T.*$";"") )as $CreatedDate
+	| if ($CreatedDate >= $WarningDate) then
+	      "Ok "
+	  else if ($CreatedDate > $CriticalDate and $CreatedDate <= $WarningDate) then
+	        "Warning "
+	     else
+	         "Critical "
+	     end
+	  end + $CreatedDate + " " + .session._id
+	'
+	getScanSessionAfterJson "$Scanner" "$GroupId" "$ProjectLabel" "$MonthAgoDate" | jq -r --argjson WarningDate "\"$WarningDate\"" --argjson CriticalDate "\"$CriticalDate\"" "$CategorizeCreatedDateJq" | sort > "$CategorizedScanDatesFile"
+	
+	OkCount=$(grep "Ok" "$CategorizedScanDatesFile" | wc -l)
+	WarningCount=$(grep "Warning" "$CategorizedScanDatesFile" | wc -l)
+	
+	if [ "$OkCount" -gt 0 ]
+	then
+		Msg="OK - ${OkCount} scan(s) in ${GroupId}/${ProjectLabel} from ${Scanner} since ${WarningDate}"
+		ReturnCode=0
+	elif [ "$WarningCount" -gt 0 ]
+	then
+		Msg="Warning - ${WarningCount} scan(s) in ${GroupId}/${ProjectLabel} from ${Scanner} between ${CriticalDate} and ${WarningDate}"
+		ReturnCode=1
+	else
+		LastScanSeenDate=$(grep Critical "$CategorizedScanDatesFile" | sort | tail -n 1 | cut -f 2 -d ' ')
+		if [ -z "$LastScanSeenDate" ]
+		then
+			Msg="CRITICAL - No scans seen in ${GroupId}/${ProjectLabel} from ${Scanner} after ${MonthAgoDate}"
+		else
+			Msg="CRITICAL - Last scan in ${GroupId}/${ProjectLabel} from ${Scanner} seen on ${LastScanSeenDate}"
+		fi
+	
+		ReturnCode=2
 	fi
+	
+	echo "$Msg"
+	return "$ReturnCode"
+}
 
-	ExitCode=2
-fi
+while getopts c:g:m:np:w:v arg
+do
+	case "$arg" in
+	     c|g|m|n|p|w|v)
+		eval "opt_${arg}='${OPTARG:=1}'"
+		;;
+	esac
+done
 
-echo "$Msg"
+shift $(($OPTIND - 1))
+
+CriticalDate=$(date --date='3 days ago' +%Y-%m-%d)
+[ -n "$opt_c" ] && CriticalDate="$opt_c"
+[ -n "$opt_v" ] && echo "${CmdName}: CriticalDate = '${CriticalDate}'" 1>&2
+
+GroupId=camris
+[ -n "$opt_g" ] && GroupId="$opt_g"
+[ -n "$opt_v" ] && echo "${CmdName}: GroupId = '${GroupId}'" 1>&2
+
+MonthAgoDate=$(date --date='2 months ago' +%Y-%m-%d)
+[ -n "$opt_m" ] && MonthAgoDateDate="$opt_m"
+[ -n "$opt_v" ] && echo "${CmdName}: MonthAgoDate = '${MonthAgoDate}'" 1>&2
+
+ProjectLabel=qa
+[ -n "$opt_p" ] && ProjectLabel="$opt_p"
+[ -n "$opt_v" ] && echo "${CmdName}: ProjectLabel = '${ProjectLabel}'" 1>&2
+
+WarningDate=$(date --date='1 day ago' +%Y-%m-%d)
+[ -n "$opt_w" ] && WarningDate="$opt_w"
+[ -n "$opt_v" ] && echo "${CmdName}: WarningDate = '${WarningDate}'" 1>&2
+
+for Scanner in "$@"
+do
+    Msg=$(checkScannerHeartbeat "$Scanner")
+    ExitCode="$?"
+
+    echo "$Msg"
+done
+
 exit "$ExitCode"
 	
