added download to fwget, added fwsearch for structured searches, updated syncFW2INDD to use fwget to download pdfs

diff --git a/bin/syncFW2INDD b/bin/syncFW2INDD
--- a/bin/syncFW2INDD
+++ b/bin/syncFW2INDD
@@ -9,19 +9,17 @@
 
 cmd=$(basename "$0")
 
-syntax="$cmd [-D][-d dir][-f inddreporttofilter][-g gear][-n][-p ProjectAnalysesFile][-v] Group/Project"
+syntax="$cmd [-D][-c CacheDir][-n][-v] [Group/Project]"
 
 function sys {
 	  [ -n "${opt_n}${opt_v}" ] && echo "$cmd : $@" 1>&2
 	  [ -n "$opt_n" ] || "$@"
 }
 
-opt_f='xxxxx'
-
-while getopts Dd:f:g:np:v arg
+while getopts c:nv arg
 do
 	case "$arg" in
-	     D|d|f|g|n|p|v)
+	     c|n|v)
 		eval "opt_${arg}=${OPTARG:=1}"
 		;;
 	esac
@@ -29,23 +27,21 @@ done
 
 shift $(($OPTIND - 1))
 
-if [ -n "$opt_g" ]
-then
-   Gear="$opt_g"
-else
-   Gear=ashsharpicv
-fi
-
 if [ -n "$1" ]
 then
 	GroupProject="$1"
 else
 	GroupProject="dwolklab/NACC-SC"
 fi
+Group=$(echo "$GroupProject" | cut -f 1 -d /)
+Project=$(echo "$GroupProject" | cut -f 2 -d /)
 
-if [ -n "$opt_d" ]
+[ -n "$opt_n" ] && opt_v=-n
+[ -n "$opt_n" ] && opt_v=-n
+
+if [ -n "$opt_c" ]
 then
-    CacheDir="$opt_d"
+    CacheDir="$opt_c"
 else
     CacheDir="${GroupProject}/${Gear}"
 fi
@@ -60,36 +56,32 @@ cd "$CacheDir"
 
 CachedPdfs=$(ls | grep '.pdf$' | sort -u)
 
-if [ -n "$opt_p" ]
-then
-    FwProjectAnalyses=$(sed 's, ,/,' "$opt_p")
-else
-    FwProjectAnalyses=$(getFWProjectAnalyses -g "$Gear" "$GroupProject" | sed 's, ,/,')
-fi
+fwsearch -r file  'group._id = '"$Group"' AND (project.label = '"$Project"') AND (file.name =~ ".*_report.pdf")' | jq -r '.[] | [ .analysis._id, .file.name] | @csv' | sort -u > /tmp/PdfWithAnalysisIds.csv
 
-FwProjectAnalysesGearPdfs=$(echo "$FwProjectAnalyses" | cut -f 3 -d / | grep '.pdf$' | sort -u)
-
-PdfsToDownload=$(diff <(echo "$FwProjectAnalysesGearPdfs") <(echo "$CachedPdfs") | grep '^< ' | cut -f 2 -d ' ')
+PdfsToDownload=$(diff <(csvcut -c 2 /tmp/PdfWithAnalysisIds.csv | sed 's/"//g' | sort -u ) <(echo "$CachedPdfs") | grep '^< ' | sed 's/< //')
 
 [ -n "${opt_n}${opt_v}" ] && echo "$cmd : PdfsToDownload = '$PdfsToDownload'" 1>&2
 
 if [ -n "$PdfsToDownload" ]
 then
+	FileIds=()
 
-	#
-	# you can't get download an analysis file without the analysis id.
-	# download all the analysis ids with their associated file names
-	# There may be multiple analysis with the same file name hummmm
-	#
-	AidFids=()
 	for i in $PdfsToDownload
 	do
-	    # Get rid of mulitple analysis with the same file name
-	    AidFid=$(echo "$FwProjectAnalyses" | grep "${i}$" | cut -f 1,2 -d / | head -n 1)
-	    AidFids+=("$AidFid")
+	    AnalysisIds=$(grep ",\"${i}\"$" /tmp/PdfWithAnalysisIds.csv | csvcut -c 1 )
+	    [ -z "$AnalysisIds" ] && echo "No Analyses Id for '${i}'" 1>&2 && continue
+
+	    for AnalysisId in $AnalysisIds
+	    do
+		AcquisitionJson=$(fwget -1 "$AnalysisId")
+		[ -z "$AcquisitionJson" ] && echo "fwget -1 \"$AnalysisId\" failed" 1>&2 && continue
+		PdfNameFileId=$(echo "$AcquisitionJson" | jq -r '.files[] | select(.name | match("report.pdf")) | [ .name, .file_id ] | @csv')
+		PdfFileId=$(echo "$PdfNameFileId" | csvcut -c 2)
+		FileIds+=( "$PdfFileId" )
+	    done
 	done
 	
-	DownloadedFiles=$(sys getFWProjectAnalyses -D "${AidFids[@]}" | awk '{print $2}')
+	sys fwget -f --download --download-dir "$CacheDir" "${FileIds[@]}"
 
 fi
 
