../bin/syncFW2INDD: s/cmd/CmdName/ so mktemp works as expected

diff --git a/bin/syncFW2INDD b/bin/syncFW2INDD
--- a/bin/syncFW2INDD
+++ b/bin/syncFW2INDD
@@ -7,12 +7,12 @@
 # + Each session only has a since analysis.  It is possible to run multiple analyses, but there is only room in the INDD for one of them.
 # 
 
-cmd=$(basename "$0")
+CmdName=$(basename "$0")
 
-syntax="$cmd [-D][-d tempdir][-c CacheDir][-g Gear][-n][-v] [Group/Project]"
+syntax="$CmdName [-D][-d tempdir][-c CacheDir][-g Gear][-n][-v] [Group/Project]"
 
 function sys {
-	  [ -n "${opt_n}${opt_v}" ] && echo "$cmd : $@" 1>&2
+	  [ -n "${opt_n}${opt_v}" ] && echo "$CmdName : $@" 1>&2
 	  [ -n "$opt_n" ] || "$@"
 }
 
@@ -66,7 +66,7 @@ fi
 
 if [ ! -d "$CacheDir" ]
 then
-    echo "$cmd : CacheDir '${CacheDir}' not found " 1>&2
+    echo "$CmdName : CacheDir '${CacheDir}' not found " 1>&2
     exit 1
 fi
 
@@ -83,7 +83,7 @@ fwsearch -r file  'group._id = '"$Group"' AND (project.label = '"$Project"') AND
 PdfsToDownloadFile="${TempDir}/PdfsToDownload"
 diff <(csvcut -c 2 "$PdfWithAnalysisIdsCsvFile" | sed 's/\"//g' | sort -u ) "$CachedPdfsFile" | grep '^< ' | sed 's/< //' > "$PdfsToDownloadFile"
 
-[ -n "${opt_n}${opt_v}" ] && echo "$cmd : PdfsToDownload = '$(cat ${PdfsToDownloadFile})'" 1>&2
+[ -n "${opt_n}${opt_v}" ] && echo "$CmdName : PdfsToDownload = '$(cat ${PdfsToDownloadFile})'" 1>&2
 
 if [ -s "$PdfsToDownloadFile" ]
 then
@@ -124,7 +124,7 @@ then
 	if ! grep -q "$InddName" <(echo "$InddPdfs")
 	then
 	    smbClientWrapper //cndr-indd.uphs.pennhealth.prv/mrireport -c 'put "'"${i}"'"' 2> /dev/null
-	    [ -n "${opt_n}${opt_v}" ] && echo "$cmd : smbClientWrapper //cndr-indd.uphs.pennhealth.prv/mrireport -c 'put \"${i}\"' \"${InddName}\"" 1>&2
+	    [ -n "${opt_n}${opt_v}" ] && echo "$CmdName : smbClientWrapper //cndr-indd.uphs.pennhealth.prv/mrireport -c 'put \"${i}\"' \"${InddName}\"" 1>&2
 	fi
     done < <(echo "$CachedPdfs")
 fi
